{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3291f054",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model Loaded!!\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [29/Nov/2021 15:41:40] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [29/Nov/2021 15:41:42] \"\u001b[37mGET /static/css/style.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [29/Nov/2021 15:41:46] \"\u001b[37mGET /static/js/dropdown.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [29/Nov/2021 15:41:46] \"\u001b[37mGET /static/js/form.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [29/Nov/2021 15:41:50] \"\u001b[37mGET /static/css/bg4.jpg HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [29/Nov/2021 15:41:54] \"\u001b[33mGET /favicon.ico HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [29/Nov/2021 23:19:00] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2021-11-29 23:23:02,881] ERROR in app: Exception on /predict [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-4-9404c7ebd65d>\", line 39, in predict\n",
      "    pred = model.predict(test_sent)\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1685, in predict\n",
      "    version_utils.disallow_legacy_graph('Model', 'predict')\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\keras\\utils\\version_utils.py\", line 129, in disallow_legacy_graph\n",
      "    raise ValueError(error_msg)\n",
      "ValueError: Calling `Model.predict` in graph mode is not supported when the `Model` instance was constructed with eager mode enabled. Please construct your `Model` instance in graph mode or call `Model.predict` with eager mode enabled.\n",
      "[2021-11-29 23:23:02,914] ERROR in app: Exception on /predict [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-4-9404c7ebd65d>\", line 39, in predict\n",
      "    pred = model.predict(test_sent)\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1685, in predict\n",
      "    version_utils.disallow_legacy_graph('Model', 'predict')\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\keras\\utils\\version_utils.py\", line 129, in disallow_legacy_graph\n",
      "    raise ValueError(error_msg)\n",
      "ValueError: Calling `Model.predict` in graph mode is not supported when the `Model` instance was constructed with eager mode enabled. Please construct your `Model` instance in graph mode or call `Model.predict` with eager mode enabled.\n",
      "127.0.0.1 - - [29/Nov/2021 23:23:08] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [29/Nov/2021 23:23:08] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n",
      "[2021-11-29 23:23:02,957] ERROR in app: Exception on /predict [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-4-9404c7ebd65d>\", line 39, in predict\n",
      "    pred = model.predict(test_sent)\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1685, in predict\n",
      "    version_utils.disallow_legacy_graph('Model', 'predict')\n",
      "  File \"C:\\Users\\kunal\\anaconda3\\lib\\site-packages\\keras\\utils\\version_utils.py\", line 129, in disallow_legacy_graph\n",
      "    raise ValueError(error_msg)\n",
      "ValueError: Calling `Model.predict` in graph mode is not supported when the `Model` instance was constructed with eager mode enabled. Please construct your `Model` instance in graph mode or call `Model.predict` with eager mode enabled.\n",
      "127.0.0.1 - - [29/Nov/2021 23:23:09] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask\n",
    "from flask import request\n",
    "from flask import jsonify\n",
    "from flask import render_template\n",
    "import os\n",
    "import sys\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "import pickle\n",
    "import pdb\n",
    "from keras.models import Model\n",
    "from keras.models import load_model\n",
    "from keras.preprocessing.sequence import pad_sequences\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "def get_model():\n",
    "\tglobal model\n",
    "\tmodel = load_model('emoji_model.h5')\n",
    "\tprint('Model Loaded!!')\n",
    "\n",
    "graph = tf.compat.v1.get_default_graph()\n",
    "\n",
    "tokenizer = pickle.load(open('tokenizer.pickle','rb'))\n",
    "\n",
    "@app.route('/')\n",
    "def home():\n",
    "\treturn render_template('view.html')\n",
    "\n",
    "@app.route('/predict',methods = ['POST'])\n",
    "def predict():\n",
    "\tglobal graph\n",
    "\tglobal tokenizer\n",
    "\twith graph.as_default():\n",
    "\t\tmaxlen = 50\n",
    "\t\ttext = request.form['name']\n",
    "\t\ttest_sent = tokenizer.texts_to_sequences([text])\n",
    "\t\ttest_sent = pad_sequences(test_sent, maxlen = maxlen)\n",
    "\t\tpred = model.predict(test_sent)\n",
    "\t\tresponse = {\n",
    "\t\t'prediction': int(np.argmax(pred))\n",
    "\t\t}\n",
    "\treturn jsonify(response)\n",
    "\n",
    "\n",
    "@app.route('/update',methods = ['POST'])\n",
    "def update():\n",
    "\tglobal graph\n",
    "\tglobal tokenizer\n",
    "\twith graph.as_default():\n",
    "\t\tmaxlen = 50\n",
    "\t\ttext = request.form['sentence']\n",
    "\t\ttest_sent = tokenizer.texts_to_sequences([text])\n",
    "\t\ttest_sent = pad_sequences(test_sent, maxlen = maxlen)\n",
    "\t\ttest_sent = np.vstack([test_sent] * 5)\n",
    "\t\tactual_output = request.form['dropdown_value']\n",
    "\t\toutput_hash = {\n",
    "\t\t\t'Happy': np.array([1.,0.,0.,0.,0.,0.,0.]),\n",
    "\t\t\t'Fear': np.array([0.,1.,0.,0.,0.,0.,0.]),\n",
    "\t\t\t'Anger': np.array([0.,0.,1.,0.,0.,0.,0.]),\n",
    "\t\t\t'Sadness': np.array([0.,0.,0.,1.,0.,0.,0.]),\n",
    "\t\t\t'Disgust': np.array([0.,0.,0.,0.,1.,0.,0.]),\n",
    "\t\t\t'Shame': np.array([0.,0.,0.,0.,0.,1.,0.]),\n",
    "\t\t\t'Guilt': np.array([0.,0.,0.,0.,0.,0.,1.]),\n",
    "\t\t\t\t\t}\n",
    "\t\tactual_output = output_hash[actual_output].reshape((1,7))\n",
    "\t\tactual_output = np.vstack([actual_output] * 5)\n",
    "\t\tmodel.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])\n",
    "\t\tmodel.fit(test_sent, actual_output, epochs = 10, batch_size = 32, shuffle=True)\n",
    "\t\tmodel.save('emoji_model.h5')\n",
    "\t\tget_model()\n",
    "\t\tresponse = {\n",
    "\t\t'update_text': 'Updated the values!! Should work in next few attempts..'\n",
    "\t\t}\n",
    "\treturn jsonify(response)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "\tget_model()\n",
    "\tapp.run(threaded=True)\n",
    "\t\t\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9e7bf2f0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
